channels:
- conda-forge
- pytorch
- pyg
- huggingface
- defaults
dependencies:
- pip=22.3
- python=3.9
- pip:
  - filelock==3.8.0
  - huggingface-hub==0.10.1
  - packaging==21.3
  - psycopg==3.1.3
  - psycopg-binary==3.1.3
  - pyparsing==3.0.9
  - pyyaml==6.0
  - regex==2022.9.13
  - sentencepiece==0.1.97
  - tokenizers==0.13.1
  - tqdm==4.64.1
  - transformers==4.23.1
name: oneforall
