python initializer.py --collection motivation
python initializer.py --collection fieldOfStudy
python initializer.py --collection occupation
python initializer.py --collection perception
python initializer.py --collection persona
python initializer.py --collection skill
python initializer.py --collection ncskills
python initializer.py --collection traits
python initializer.py --collection values
python initializer.py --collection broad_activities