channels:
- pytorch
- pyg
- huggingface
- conda-forge
- defaults
dependencies:
- pytorch=1.12.1
- torchaudio=0.12.1
- torchvision=0.13.1
- transformers=4.23.1
- python=3.9
- pip:
  - psycopg==3.1.3
  - psycopg-binary==3.1.3
  - pyyaml==6.0
name: oneforall
