channels:
- conda-forge
- pytorch
- pyg
- defaults
dependencies:
- pip=22.3
- python=3.9
- pip:
  - accelerate==0.12.0
  - filelock==3.8.0
  - huggingface-hub==0.9.1
  - packaging==21.3
  - psutil==5.9.2
  - psycopg==3.1.3
  - psycopg-binary==3.1.3
  - pyparsing==3.0.9
  - pyyaml==6.0
  - regex==2022.8.17
  - sentencepiece==0.1.97
  - tokenizers==0.12.1
  - tqdm==4.64.1
  - transformers==4.22.2
name: oneforall
